"""Cleanup for iteration 13 test artifacts: TEST_ user, its bookings, TEST_ templates/instances,
and the settings_audit rows generated by the automated tests."""
import asyncio
import os
import sys

sys.path.insert(0, "/app/backend")


async def main():
    from core import db
    u = await db.users.find_one({"email": "test_wl_student@example.com"})
    if u:
        r = await db.bookings.delete_many({"user_id": u["id"]})
        print("deleted bookings:", r.deleted_count)
        await db.users.delete_one({"id": u["id"]})
        print("deleted TEST_ user")
    tpls = await db.class_templates.find({"title": {"$regex": "^TEST_"}}).to_list(50)
    for t in tpls:
        await db.class_instances.delete_many({"template_id": t["id"]})
        await db.class_templates.delete_one({"id": t["id"]})
    print("deleted TEST_ templates:", len(tpls))
    r = await db.settings_audit.delete_many({"keys": ["reminder_lead_minutes"]})
    print("deleted audit rows (reminder_lead_minutes only):", r.deleted_count)
    print("remaining audit rows:", await db.settings_audit.count_documents({}))


asyncio.run(main())
